name: Shell Commands

on: [push]

jobs: 
  run-shell-command: 
    runs-on: ubuntu-latest
    steps: 
      - name: eccho a string
        run: eecho "Hello world"
      - name: multirun script
        run: |
          node -v
          npm -v
